name: AmazingTitles
api-version: 1.13
version: 4.0
main: sk.m3ii0.amazingtitles.code.internal.Booter
author: M3II0
commands:
  amazingtitles:
    permission: "amazingtitles.command"
    aliases:
      - at