name: AmazingTitles
api-version: 1.16
version: 3.0
main: sk.m3ii0.amazingtitles.code.AmazingTitles
author: M3II0
commands:
  amazingtitles:
    permission: "amazingtitles.admin"
    aliases:
      - at